# Artificial Neural Network

### Importing the libraries

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
from sklearn.preprocessing import LabelEncoder
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix, accuracy_score

## Part 1 - Data Preprocessing

### Importing the dataset

In [2]:
dataset = pd.read_csv('Churn_Modelling.csv')
dataset

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

SELECTING RELEVANT FEATURES

In [3]:
y = dataset['Exited']
X = dataset.drop(columns=['RowNumber','Exited', 'CustomerId', 'Surname'])
X , X_new, y, y_new = train_test_split(X, y, test_size = 0.5, random_state = 42)

In [4]:
print(X)

      CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
7660          458     Spain    Male   36       5       0.00              2   
275           706     Spain  Female   37       7       0.00              2   
2985          840    France    Male   30       8  136291.71              1   
5646          526   Germany  Female   35       9  118536.40              1   
5849          665    France    Male   51       2       0.00              1   
...           ...       ...     ...  ...     ...        ...            ...   
5734          768    France    Male   54       8   69712.74              1   
5191          682    France  Female   58       1       0.00              1   
5390          735    France  Female   38       1       0.00              3   
860           667    France    Male   43       8  190227.46              1   
7270          697   Germany    Male   51       1  147910.30              1   

      HasCrCard  IsActiveMember  EstimatedSalary  
7660        

In [5]:
print(y)

7660    0
275     0
2985    0
5646    1
5849    0
       ..
5734    0
5191    0
5390    1
860     1
7270    0
Name: Exited, Length: 5000, dtype: int64


### Encoding categorical data

Label Encoding the "Gender" column

In [6]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X['Gender'] = le.fit_transform(X['Gender'])
# weight issue

In [7]:
print(X)

      CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
7660          458     Spain       1   36       5       0.00              2   
275           706     Spain       0   37       7       0.00              2   
2985          840    France       1   30       8  136291.71              1   
5646          526   Germany       0   35       9  118536.40              1   
5849          665    France       1   51       2       0.00              1   
...           ...       ...     ...  ...     ...        ...            ...   
5734          768    France       1   54       8   69712.74              1   
5191          682    France       0   58       1       0.00              1   
5390          735    France       0   38       1       0.00              3   
860           667    France       1   43       8  190227.46              1   
7270          697   Germany       1   51       1  147910.30              1   

      HasCrCard  IsActiveMember  EstimatedSalary  
7660        

ONE HOT ENCODING THE GEOGRAPHY COLUMN

In [8]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [9]:
print(X)

[[0.000000e+00 0.000000e+00 1.000000e+00 ... 1.000000e+00 0.000000e+00
  7.972378e+04]
 [0.000000e+00 0.000000e+00 1.000000e+00 ... 1.000000e+00 1.000000e+00
  1.108993e+05]
 [1.000000e+00 0.000000e+00 0.000000e+00 ... 1.000000e+00 0.000000e+00
  5.411338e+04]
 ...
 [1.000000e+00 0.000000e+00 0.000000e+00 ... 0.000000e+00 0.000000e+00
  9.222012e+04]
 [1.000000e+00 0.000000e+00 0.000000e+00 ... 1.000000e+00 0.000000e+00
  9.750804e+04]
 [0.000000e+00 1.000000e+00 0.000000e+00 ... 1.000000e+00 1.000000e+00
  5.358114e+04]]


### Splitting the dataset into the Training set and Test set

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

### Feature Scaling

In [11]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Part 2 - Building the ANN

### Initializing the ANN

In [12]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [13]:
ann.add(tf.keras.layers.Dense(units = 32, activation='relu'))

### Adding the second hidden layer

In [14]:
ann.add(tf.keras.layers.Dense(units=12, activation='relu'))

### Adding the output layer

In [15]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

## Part 3 - Training the ANN

### Compiling the ANN

In [16]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

### Training the ANN on the Training set

In [17]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100, validation_split = 0.2)

Epoch 1/100
100/100 [==============================] - 2s 5ms/step - loss: 0.4994 - accuracy: 0.7903 - val_loss: 0.4556 - val_accuracy: 0.8050
Epoch 2/100
100/100 [==============================] - 0s 3ms/step - loss: 0.4430 - accuracy: 0.8075 - val_loss: 0.4349 - val_accuracy: 0.8188
Epoch 3/100
100/100 [==============================] - 0s 3ms/step - loss: 0.4255 - accuracy: 0.8181 - val_loss: 0.4234 - val_accuracy: 0.8238
Epoch 4/100
100/100 [==============================] - 0s 3ms/step - loss: 0.4131 - accuracy: 0.8263 - val_loss: 0.4152 - val_accuracy: 0.8288
Epoch 5/100
100/100 [==============================] - 0s 3ms/step - loss: 0.4035 - accuracy: 0.8288 - val_loss: 0.4068 - val_accuracy: 0.8313
Epoch 6/100
100/100 [==============================] - 0s 3ms/step - loss: 0.3939 - accuracy: 0.8341 - val_loss: 0.4008 - val_accuracy: 0.8313
Epoch 7/100
100/100 [==============================] - 0s 3ms/step - loss: 0.3852 - accuracy: 0.8400 - val_loss: 0.3941 - val_accuracy: 0.8400

## Part 4 - Making the predictions and evaluating the model

### Predicting the result of a single observation

**Homework**

Use our ANN model to predict if the customer with the following informations will leave the bank: 

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: \$ 60000

Number of Products: 2

Does this customer have a credit card? Yes

Is this customer an Active Member: Yes

Estimated Salary: \$ 50000

So, should we say goodbye to that customer?

**Solution**

In [18]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

1/1 [==============================] - 0s 159ms/step
[[False]]


Therefore, our ANN model predicts that this customer stays in the bank!

**Important note 1:** Notice that the values of the features were all input in a double pair of square brackets. That's because the "predict" method always expects a 2D array as the format of its inputs. And putting our values into a double pair of square brackets makes the input exactly a 2D array.

**Important note 2:** Notice also that the "France" country was not input as a string in the last column but as "1, 0, 0" in the first three columns. That's because of course the predict method expects the one-hot-encoded values of the state, and as we see in the first row of the matrix of features X, "France" was encoded as "1, 0, 0". And be careful to include these values in the first three columns, because the dummy variables are always created in the first columns.

### Predicting the Test set results

In [19]:
y_pred = ann.predict(X_test)
y_pred = np.where(y_pred > 0.5, 1, 0)
print(np.concatenate((y_pred, y_test.values.reshape(-1, 1))))

32/32 [==============================] - 0s 2ms/step
[[0]
 [1]
 [1]
 ...
 [0]
 [1]
 [1]]


### Making the Confusion Matrix

In [20]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)*100

[[707  76]
 [ 88 129]]


83.6

# Let's work on some new data

ENCODING THE CATEGORICAL COLUMNS

In [21]:
le = LabelEncoder()
X_new['Gender'] = le.fit_transform(X_new['Gender'])
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X_new = np.array(ct.fit_transform(X_new))

SPLITTING THE NEW DAtASET INTO TRAINING AND TEST

we can first use this new data to predict the output using the model and then use them as new input for the model but I'll just do the input part to remove clutter.


In [22]:
X_new_train, X_new_test, y_new_train, y_new_test = train_test_split(X_new, y_new, test_size = 0.3, random_state = 42)

FEATURE SCALING

In [23]:
X_new_train = sc.fit_transform(X_new_train)
X_new_test = sc.transform(X_new_test)

TRAINING THE MODEL USING NEW INPUT

In [24]:
ann.fit(X_new_train, y_new_train, batch_size = 32, epochs = 100, validation_split = 0.2)

Epoch 1/100
88/88 [==============================] - 1s 6ms/step - loss: 0.3923 - accuracy: 0.8446 - val_loss: 0.3902 - val_accuracy: 0.8429
Epoch 2/100
88/88 [==============================] - 0s 3ms/step - loss: 0.3689 - accuracy: 0.8532 - val_loss: 0.3905 - val_accuracy: 0.8386
Epoch 3/100
88/88 [==============================] - 0s 3ms/step - loss: 0.3566 - accuracy: 0.8536 - val_loss: 0.3831 - val_accuracy: 0.8486
Epoch 4/100
88/88 [==============================] - 0s 3ms/step - loss: 0.3478 - accuracy: 0.8582 - val_loss: 0.3801 - val_accuracy: 0.8357
Epoch 5/100
88/88 [==============================] - 0s 3ms/step - loss: 0.3405 - accuracy: 0.8632 - val_loss: 0.3839 - val_accuracy: 0.8314
Epoch 6/100
88/88 [==============================] - 0s 3ms/step - loss: 0.3341 - accuracy: 0.8632 - val_loss: 0.3820 - val_accuracy: 0.8300
Epoch 7/100
88/88 [==============================] - 0s 3ms/step - loss: 0.3294 - accuracy: 0.8661 - val_loss: 0.3846 - val_accuracy: 0.8371
Epoch 8/100
8

SAMPLE INPUT

In [25]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

1/1 [==============================] - 0s 32ms/step
[[False]]


# Calculating Accuracy of the model using the new data

In [26]:
y_pred_new = ann.predict(X_new_test)
y_pred_new = np.where(y_pred_new > 0.5, 1, 0)
cm = confusion_matrix(y_new_test, y_pred_new)
print(cm)
accuracy_score(y_new_test, y_pred_new)*100

47/47 [==============================] - 0s 2ms/step
[[1114   78]
 [ 151  157]]


84.73333333333333

# Let's check again the accuracy score for X_test (Original Data)

If it increases, out model is learning

In [27]:
y_pred = ann.predict(X_test)
y_pred = np.where(y_pred > 0.5, 1, 0)
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)*100

32/32 [==============================] - 0s 1ms/step
[[716  67]
 [ 96 121]]


83.7

# Checking Accuracy of the model on the whole dataset

In [28]:
X_n = dataset.iloc[:, 3:-1].values
y_n = dataset.iloc[:, -1].values

X_n[:, 2] = le.fit_transform(X_n[:, 2])
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X_n = np.array(ct.fit_transform(X_n))

X_n_train, X_n_test, y_n_train, y_n_test = train_test_split(X_n, y_n, test_size = 0.3, random_state = 0)

X_n = sc.fit_transform(X_n)

y_pr = ann.predict(X_n)
y_pr = (y_pr > 0.5)
cm = confusion_matrix(y_n, y_pr)
print(cm)
accuracy_score(y_n, y_pr )*100


313/313 [==============================] - 1s 2ms/step
[[7512  451]
 [ 929 1108]]


86.2