In [32]:
import numpy as np
import pandas as pd
import tensorflow as tf
from sklearn.preprocessing import LabelEncoder
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix, accuracy_score

In [33]:
dataset = pd.read_csv('Churn_Modelling.csv')
dataset

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [34]:
y = dataset['Exited']
X = dataset.drop(columns=['RowNumber','Exited', 'CustomerId', 'Surname'])
X , X_new, y, y_new = train_test_split(X, y, test_size = 0.5, random_state = 42)

In [35]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X['Gender'] = le.fit_transform(X['Gender'])

In [36]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [37]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

In [38]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

# K-NN

In [39]:
from sklearn.neighbors import KNeighborsClassifier
classifier_KNN = KNeighborsClassifier(n_neighbors=5,metric = 'minkowski',p=2)
classifier_KNN.fit(X_train, y_train)

KNeighborsClassifier()

# Logistic Regression 

In [40]:
from sklearn.linear_model import LogisticRegression
classifier_logR = LogisticRegression(random_state = 0)
classifier_logR.fit(X_train, y_train)

LogisticRegression(random_state=0)

# Linear SVM

In [41]:
from sklearn.svm import SVC
classifier_LSVM = SVC(kernel='linear', random_state = 0)
classifier_LSVM.fit(X_train, y_train)

SVC(kernel='linear', random_state=0)

# Non-Linear SVM

In [42]:
from sklearn.svm import SVC
classifier_PSVM = SVC(kernel='poly', random_state = 0)
classifier_PSVM.fit(X_train, y_train)

SVC(kernel='poly', random_state=0)

In [43]:
from sklearn.svm import SVC
classifier_RSVM = SVC(kernel='rbf', random_state = 0)
classifier_RSVM.fit(X_train, y_train)

SVC(random_state=0)

# Decision Tree

In [44]:
from sklearn.tree import DecisionTreeClassifier
classifier_DT = DecisionTreeClassifier(criterion='entropy' , random_state=0)
classifier_DT.fit(X_train , y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

# Random Forest

In [54]:
from sklearn.ensemble import RandomForestClassifier
classifier_RF = RandomForestClassifier(n_estimators=1000,criterion='entropy',random_state=0)
classifier_RF.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=1000, random_state=0)

In [55]:
y_pred_logR = classifier_logR.predict(X_test)
y_pred_KNN = classifier_KNN.predict(X_test)
y_pred_LSVM = classifier_LSVM.predict(X_test)
y_pred_PSVM = classifier_PSVM.predict(X_test)
y_pred_RSVM = classifier_RSVM.predict(X_test)
y_pred_DT = classifier_DT.predict(X_test)
y_pred_RF = classifier_RF.predict(X_test)
# print(y_pred)
# print(y_test)
# print(np.concatenate((y_pred, y_test)))

In [47]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred_KNN)
print('FOR K-NN')
print(cm)
accuracy_score(y_test, y_pred_KNN)

FOR K-NN
[[743  40]
 [131  86]]


0.829

In [48]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred_logR)
print('FOR LOGISTIC REGRESSION')
print(cm)
accuracy_score(y_test, y_pred_logR)

FOR LOGISTIC REGRESSION
[[754  29]
 [166  51]]


0.805

In [49]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred_LSVM)
print('FOR Linear SVM')
print(cm)
accuracy_score(y_test, y_pred_LSVM)

FOR Linear SVM
[[783   0]
 [217   0]]


0.783

In [50]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred_PSVM)
print('FOR POLY KERNEL SVM')
print(cm)
accuracy_score(y_test, y_pred_PSVM)

FOR POLY KERNEL SVM
[[766  17]
 [135  82]]


0.848

In [51]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred_RSVM)
print('FOR RBF KERNEL SVM')
print(cm)
accuracy_score(y_test, y_pred_RSVM)

FOR RBF KERNEL SVM
[[759  24]
 [129  88]]


0.847

In [52]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred_DT)
print('FOR DECISION TREE')
print(cm)
accuracy_score(y_test, y_pred_DT)

FOR DECISION TREE
[[673 110]
 [ 90 127]]


0.8

In [56]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred_RF)
print('FOR RANDOM FOREST')
print(cm)
accuracy_score(y_test, y_pred_RF)

FOR RANDOM FOREST
[[756  27]
 [110 107]]


0.863